import Head from "next/head";
import Banner from "../components/Banner";

import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Services from "../components/Services";

import Testimonial from "../components/Testimonial";
import About from "../components/About";
import Register from "../components/Register";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>E Pay| Code Battle</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />
      <About />

      <Services />
      <Register />
      
      <FAQ />
      <Testimonial />
      <Footer /> 

    </div>
  );
}
