import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-dark">
      <Head>
        <title>SMCON | Code Battle</title>
      
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <h1>Hello World</h1>
    </div>
  )
}
